--CREATE DATABASE COMERCIO_DW
--USE COMERCIO_DW

--CREATE SCHEMA DW
ALTER DATABASE COMERCIO_DW 

CREATE TABLE DW.DIM_VENDEDOR(
	IDSK		INT PRIMARY KEY IDENTITY
   ,IDVENDEDOR	INT
   ,FIM			DATETIME
   ,NOME		VARCHAR(100)
   ,SEXO		VARCHAR(20)
   ,IDGERENTE	INT
) 

CREATE TABLE DW.DIM_NOTA(
	IDSK	INT PRIMARY KEY IDENTITY
   ,IDNOTA	INT
) 

CREATE TABLE DW.DIM_FORMA(
	IDSK	INT PRIMARY KEY IDENTITY
   ,IDFORMA	INT
   ,FORMA	VARCHAR(30)
) 

CREATE TABLE DW.DIM_CLIENTE(
	IDSK		INT PRIMARY KEY IDENTITY
   ,IDCLIENTE	INT
   ,INICIO		DATETIME
   ,FIM			DATETIME
   ,NOME		VARCHAR(100)
   ,SEXO		VARCHAR(20)
   ,EMAIL		VARCHAR(50)
   ,NASCIMENTO	DATE
   ,CIDADE		VARCHAR(100)
   ,ESTADO		VARCHAR(30)
   ,REGIAO		VARCHAR(30)
) 

CREATE TABLE CATEGORIA(
    IDCATEGORIA	INT PRIMARY KEY 
   ,NOME		VARCHAR(50)
) 

CREATE TABLE DW.DIM_PRODUTO(
	IDSK			INT PRIMARY KEY IDENTITY
   ,IDPRODUTO		INT
   ,FORMA			VARCHAR(30)
   ,INICIO			DATETIME
   ,FIM				DATETIME
   ,NOME			VARCHAR(100)
   ,VALOR_UNITARIO	NUMERIC(10,2)
   ,CUSTO_MEDIO		NUMERIC(10,2)
   ,IDCATEGORIA		INT
) 

CREATE TABLE DW.DIM_FORNECEDOR(
	 IDSK			INT PRIMARY KEY IDENTITY
   , IDFORNECEDOR	INT
   , INICIO			DATETIME
   , FIM			DATETIME
   , NOME			VARCHAR(50)
) 

CREATE TABLE DW.DIM_TEMPO(
	  IDSK				INT PRIMARY KEY IDENTITY
	, DATE				DATE
	, DIA				CHAR(2)
	, DIASEMANA			VARCHAR(10)
	, MES				CHAR(2)
	, NOMEMES			VARCHAR(20)
	, QUARTO			TINYINT
	, NOMEQUARTO		VARCHAR(20)
	, ANO				CHAR(3)
	, ESTACAOANO		VARCHAR(20)
	, FIMSEMANA			CHAR(3)
	, DATACOMPLETA		VARCHAR(10)
) 


CREATE TABLE DW.FATO(
	  IDNOTA			INT 
	, IDCLIENTE		INT 
	, IDVENDEDOR		INT 
	, IDFORMA			INT 
	, IDPRODUTO		INT 
	, IDFORNECEDOR		INT 
	, IDTEMPO			INT 
	, QUANTIDADE		INT
	, TOTAL_ITEM		NUMERIC(10,2)
	, CUSTO_TOTAL		NUMERIC(10,2)
	, LUCRO_TOTAL		NUMERIC(10,2)

	 CONSTRAINT FK_FATO_DIM_NOTA	   FOREIGN KEY(IDNOTA) REFERENCES DW.DIM_NOTA		 (IDSK)
	,CONSTRAINT FK_FATO_DIM_CLIENTE	   FOREIGN KEY(IDCLIENTE) REFERENCES DW.DIM_CLIENTE	 (IDSK)
	,CONSTRAINT FK_FATO_DIM_VENDEDOR   FOREIGN KEY(IDVENDEDOR) REFERENCES DW.DIM_VENDEDOR	 (IDSK)
	,CONSTRAINT FK_FATO_DIM_FORMA	   FOREIGN KEY(IDFORMA) REFERENCES DW.DIM_FORMA		 (IDSK)
	,CONSTRAINT FK_FATO_DIM_PRODUTO	   FOREIGN KEY(IDPRODUTO) REFERENCES DW.DIM_PRODUTO	 (IDSK)
	,CONSTRAINT FK_FATO_DIM_FORNECEDOR FOREIGN KEY(IDFORNECEDOR) REFERENCES DW.DIM_FORNECEDOR (IDSK)
	,CONSTRAINT FK_FATO_DIM_TEMPO	   FOREIGN KEY(IDTEMPO) REFERENCES dbo.DIM_TEMPO		 (IDSK)
) 


