--CREATE DATABASE COMERCIO_DW
--USE COMERCIO_DW

--CREATE SCHEMA DW
ALTER DATABASE COMERCIO_DW ADD FILEGROUP DW

CREATE SCHEMA DW

CREATE TABLE DW.DIM_VENDEDOR(
	IDSK		INT PRIMARY KEY IDENTITY
   ,IDVENDEDOR	INT
   ,FIM			DATETIME
   ,NOME		VARCHAR(100)
   ,SEXO		VARCHAR(20)
   ,IDGERENTE	INT
) ON [DW]

CREATE TABLE DW.DIM_NOTA(
	IDSK	INT PRIMARY KEY IDENTITY
   ,IDNOTA	INT
) ON [DW]

CREATE TABLE DW.DIM_FORMA(
	IDSK	INT PRIMARY KEY IDENTITY
   ,IDFORMA	INT
   ,FORMA	VARCHAR(30)
) ON [DW]

CREATE TABLE DW.DIM_CLIENTE(
	IDSK		INT PRIMARY KEY IDENTITY
   ,IDCLIENTE	INT
   ,INICIO		DATETIME
   ,FIM			DATETIME
   ,NOME		VARCHAR(100)
   ,SEXO		VARCHAR(20)
   ,EMAIL		VARCHAR(50)
   ,NASCIMENTO	DATE
   ,CIDADE		VARCHAR(100)
   ,ESTADO		VARCHAR(30)
   ,REGIAO		VARCHAR(30)
) ON [DW]

CREATE TABLE CATEGORIA(
    IDCATEGORIA	INT PRIMARY KEY 
   ,NOME		VARCHAR(50)
) ON [DW]

CREATE TABLE DW.DIM_PRODUTO(
	IDSK			INT PRIMARY KEY IDENTITY
   ,IDPRODUTO		INT
   ,FORMA			VARCHAR(30)
   ,INICIO			DATETIME
   ,FIM				DATETIME
   ,NOME			VARCHAR(100)
   ,VALOR_UNITARIO	NUMERIC(10,2)
   ,CUSTO_MEDIO		NUMERIC(10,2)
   ,IDCATEGORIA		INT
) ON [DW]